name: firebase_dart_admin_auth_sdk
description: A Dart SDK for Firebase Admin Authentication, enabling secure server-side authentication and user management for Dart-based backend applications.
version: 0.0.1-pre+5
repository: https://github.com/aortem/firebase-dart-admin-auth-sdk

environment:
  sdk: ^3.5.2

# Add regular dependencies here.

dependencies:
#------------------ STANDARD FEATURES---------------------------------
## There are three standard libraries.  Each one can be used with a different xxx 

  ds_standard_features: ^0.0.1-pre+11 #Standard Dart Team Utilities For HTTP //Default
  build_web_compilers: ^4.0.11
  jwt_generator: ^0.0.3
#  ds_standard_features_web: ^0.0.1-pre+1 #Standard Dart Team Utilities for //Uncomment for WEB
#  ds_standard_features_grpc: ^0.0.1-pre+1 #Standard Dart Team Utilities for //Uncomment for GRPC
  

#------------------ TESTING FEATURES---------------------------------

dev_dependencies:
  ds_tools_testing: ^0.0.1-pre+2 #Standard Dart Team Testing Tools
  test_reporter: any #required to generate JUnit report 
  http: any
